### ISSUE TITLE
Getting error when trying to install opencv

### ISSUE THREAD

**Issue by jaleedriaz** [paulhayes/copterface#2]
Hi there !
I got an error when I try to install opencv. It said that node-gyp fails to rebuild the repo.
Because I don't have the package node-gyp installed in my system and I can't install it.
See my screenshot :

![opencv_error](https://f.cloud.github.com/assets/6131571/1707436/b371e476-60fd-11e3-8038-958e1d16abb1.png)

Plz help me, I don't have any idea to solve this problem. I am new in that field.
Thanks

**Comment by RPEK001** [comment]
Is there a solution around this issue? Thanks!
@jaleedriaz @paulhayes

**Comment by paulhayes** [comment]
I've been refactoring copterface to use an alternative lib. I'd meant to push but had got distracted by life. Will do it soon.

**Comment by paulhayes** [comment]
Done. Only took me a year to get round to it!
