### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by cyberphantom** [paulhayes/copterface#4]
Hi Paul,

That's really cool, I'm trying to do something similar,  but with unknown objects that I assign  using stylus on the canvas. 
So, I was trying to find the part that controlling the drone so that the face will be in the middle of the camera streaming but I couldn't find it or may be I miss understand what you are trying to do here. So is there any part in your code that attempts to control the drone so that to make the face in the middle of the png stream with a certain ratio?

Thanks in advance,

**Comment by paulhayes** [comment]
Right yes! I forgot to put that in the example when I refactored. Here's what the code that did that used to look like, it's pretty trivial, once you have the face position ( provided by info argument in the callback ).

https://github.com/paulhayes/copterface/commit/17eaa699aac0c63da89494b6c5da725d33d1b247
